import type { Metadata } from "next";

import "./globals.css";
import { UserProvider } from "@/Context/UserInfoContext";
import RouteLoading from "./Components/global/RouteLoading";


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app , made by AJHEER",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
       <UserProvider>
        <main>
          <RouteLoading>
          {children}
          </RouteLoading>
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
