import type { Metadata } from "next";

import "./globals.css";
import { UserProvider } from "@/Context/UserInfoContext";
import RouteLoading from "./Components/global/RouteLoading";
import { LoadingProvider } from "@/Context/LoadingContext";
import ResetLoading from "./Components/layout/ResetLoading";
import { PostHogProvider } from "./providers";
import { PostHogPageView } from "./PostHogPageView";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app , made by AJHEER",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PostHogProvider>
          <Suspense fallback={null}>
            <PostHogPageView />
          </Suspense>
          <UserProvider>
            <main>
              <LoadingProvider>
                <RouteLoading>
                  <ResetLoading />
                  {children}
                </RouteLoading>
              </LoadingProvider>
            </main>
          </UserProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
