import type { Metadata } from "next";
import "../globals.css";
import LayoutChild from "./components/Layout/LayoutChid";

export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
            <LayoutChild >
              {children}
            </LayoutChild>
        </main>
      </body>
    </html>
  );
}
